---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: false
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths: [ 'bin/', 'assets/fonts/', 'assets/img/', 'assets/jspm/' ]
