---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
    - f1a0faef7683a713d0a8f63bc6c4b123
    - 8e468e58976f443661237fe897f13457
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: false
  scss-lint:
    enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- 'bin/**/*'
- 'assets/fonts/**/*'
- 'assets/img/**/*'
- 'assets/jspm/**/*'
- 'assets/scss/vendor/**/*'
- 'hbs/**/*.hbs'
- 'static/**/*'
- '**/*.md'
- 'config.js'
