---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
    - f1a0faef7683a713d0a8f63bc6c4b123
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: false
  scss-lint:
    enabled: false
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- 'bin/**/*'
- 'md/**/*'
- 'assets/fonts/**/*'
- 'assets/img/**/*'
- 'assets/jspm/**/*'
- 'config.js'
