---
  env:
    commonjs: true
    es6:      true
    node:     true
  extends: "eslint:recommended"
  parserOptions:
    ecmaVersion: 6
    sourceType: "module"
  rules:
    arrow-body-style:
      - error
      - "always"
    arrow-parens:
      - error
      - "always"
    arrow-spacing:
      - error
      -
        before: true
        after: true
    brace-style:
      - 1
      - "stroustrup"
    block-scoped-var: error
    block-spacing: error
    camelcase: 1
    comma-dangle:
      - error
      - "always-multiline"
    comma-spacing:
      - error
      -
        before: false
        after: true
    comma-style:
      - error
      - "last"
    computed-property-spacing:
      - error
      - "never"
    eol-last: 0
    indent:
      - error
      - 2
      -
        SwitchCase: 1
    keyword-spacing: error
    max-nested-callbacks:
      - 1
      - 3
    max-params:
      - error
      - 3
    max-depth:
      - error
      - 3
    new-cap: error
    new-parens: error
    no-cond-assign: error
    no-console: 1
    no-constant-condition: error
    no-control-regex: error
    no-debugger: 1
    no-dupe-args: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-empty-character-class: error
    no-empty: error
    no-ex-assign: error
    no-extra-boolean-cast: error
    no-extra-parens: 0
    no-extra-semi: error
    no-func-assign: error
    no-inner-declarations: error
    no-invalid-regexp: error
    no-irregular-whitespace: error
    no-mixed-spaces-and-tabs:
      - error
      - "smart-tabs"
    no-negated-in-lhs: error
    no-obj-calls: error
    no-regex-spaces: error
    no-spaced-func: error
    no-sparse-arrays: error
    no-unexpected-multiline: error
    no-unreachable: error
    no-use-before-define: error
    use-isnan: error
    no-floating-decimal: 1
    no-magic-numbers:
      - 1
      -
        ignore:
          - -1
          - 0
          - 1
          - 2
    no-nested-ternary: error
    no-plusplus: 1
    no-throw-literal: error
    no-trailing-spaces: error
    no-underscore-dangle: 0
    no-unused-vars:
      - error
      -
        args: "none"
    object-curly-spacing:
      - error
      - "always"
    object-shorthand:
      - error
      - "never"
    one-var:
      - error
      - "never"
    quote-props:
      - error
      - "consistent-as-needed"
      -
        keywords: true
    quotes:
      - 1
      - "single"
    radix: error
    semi:
      - error
      - "always"
    semi-spacing:
      - error
      -
        before: false
        after: true
    space-before-blocks: error
    space-before-function-paren:
      - 1
      -
        anonymous: "always"
        named: "never"
    space-infix-ops:
      - error
      -
        int32Hint: false
    space-unary-ops: error
    valid-jsdoc:
      - error
      -
        requireReturn: false
        requireParamDescription: false
        requireReturnDescription: false
    valid-typeof: error
    wrap-iife:
      - error
      - "any"
    yoda:
      - error
      - "never"
