sudo: false
language: node_js
cache:
  directories:
  - assets/jspm
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX="g++-4.8"
  - GITHUB_PAGES_REPO="https://github.com/davidosomething/davidosomething.github.io.git"
  - secure: foSclTYU3qgST+Oot0QgnI8cTOvbGLCjcDubP9bN1Nts5VB9PAk/YFq817prmkpSlfvDUkCT5uf8pOvboN3Ufa9ZRhKW8CcqXlaUpgrAhvbDp/OO3WgFxWZVPBPtNZveaJcrYoiMtOSdpizo6X43EGgp+pao3qK0fTYekM+nluLg2o3T9einDCKSbf9+sp0rb8TwKmy6WQNtK3PMtDrwJufCPiwTg8ZlkZ7SfRkd1LqV6+OWUDr++AOCFk4xf2v7dknFykzYj4fZAUi+c/ifz+38tPEwCLUNRtA81hH0hOc1xwk/zYxQ0lSEdvKAehnP2fEkhZYFrl/e3h8QsI7y0NnO3Yq3S7cW6sLwWLsz9ugW6M6tlpARVsn708yInpU/zFlq8zDMMFDQ8lpcBdElIcC4mkxrSIulbWBZVINuVgVXjVLXkUxMRi5HOeHOcAZWggzxmAsVqQenc6yn2Ewo5I8DyftipVtfs0gghz64czyC58bXv3iUzfJb879mtDGGJlbuHpTNt8BhOx205KKDWNVv3cieDJD2nyEBLpO5b4lrQui5p6+oZ2AdUyBzbYnBr1/pudFOxLAmnEjdeJEilgkspNGvOLBGPlRAcfdKFOn/D9URqBdG+rc1xOp9cJ2ZMFlPo2Iy9PoyTtMC1Fm0JO1dmkD9PFNIdo9xAQ62SPc=
branches:
  only:
  - master
  - dev
before_script:
- npm install -g gulp
install:
- npm install
- npm run travis-jspm-config
- npm run travis-jspm-install
script:
- gulp lint:css
- gulp lint:js
- gulp
after_success:
- echo "Build \#${TRAVIS_BUILD_NUMBER} of https://github.com/davidosomething/davidosomething.github.io/commit/${TRAVIS_COMMIT}"
- |
  if [ "$TRAVIS_BRANCH" = "master" ]; then
    npm run deploy-surge &

    openssl aes-256-cbc -K $encrypted_157bbe5ff2f8_key -iv $encrypted_157bbe5ff2f8_iv -in lib/id_rsa.enc -out ~/.ssh/id_rsa -d
    chmod u=rw,og= ~/.ssh/id_rsa
    echo "Host github.com"              >> ~/.ssh/config
    echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
    git config user.name "TravisCI"
    git config user.email "travis@travis-ci.org"
    GITHUB_PAGES_COMMIT_MESSAGE="Deploy build ${TRAVIS_BUILD_NUMBER} of https://github.com/davidosomething/davidosomething.github.io/commit/${TRAVIS_COMMIT}" npm run travis-deploy-github

    wait
  fi
